- README.md
- src/pages/Landing/NetworkStatus/index.tsx
This adds in the base documentation for the repo
- Ethereum Foundation to add license information
resolves #33
> Base documentation & quick fix for the validator count

- .eslintrc.js
- src/pages/Acknowledgements/AcknowledgementSection.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/ConnectWallet/index.tsx
- src/pages/GenerateKeys/LinuxInstructions.tsx
- src/pages/GenerateKeys/MacInstructions.tsx
- src/pages/GenerateKeys/WindowsInstructions.tsx
- src/pages/GenerateKeys/index.tsx
- src/pages/Landing/Hero.tsx
- src/pages/Landing/StakingRewards.tsx
- src/pages/NotFound.tsx
- src/pages/Summary/index.tsx
- src/pages/Transactions/Keylist/index.tsx
- src/pages/UploadValidator/Dropzone.tsx
- turns off `react/jsx-one-expression-per-line` for readability
- cleans up eslint err/warnings
> Lint cleanup & adjust config

- src/pages/GenerateKeys/WindowsInstructions.tsx
- Adds in windows commands from @qnou 
Fixes #67
> Generate keys windows commands

- package.json
- src/pages/GenerateKeys/TerminalUI.tsx
- yarn.lock
- udpate wordwrap to support small screensizes
- fix copy command
- remove typewriter effect
resolves #69 , #59
> Commands Interface Fixes

- src/pages/Acknowledgements/AcknowledgementSection.tsx
- src/pages/Congratulations/index.tsx
- src/pages/GenerateKeys/index.tsx
- src/pages/Summary/index.tsx
- src/pages/Transactions/Keylist/index.tsx
- src/pages/Transactions/index.tsx
- yarn.lock
- Replaces the redirect logic with a CTA that allows the user to complete the flow.
- Setup conditional disabled button, skip warnings if not all transitions are complete, and a 🎉 continue button once all tx have confirmed
- Creates a scrollable section in the event the user has a long validator list. A short transaction table allows the bottom buttons to be visible.
- Color and emoji touches
- Cleans up yarn lock from the last PR merged into dev
> Rework Transaction flow

- package.json
- src/Routes.tsx
- src/pages/FAQ/index.jsx
- src/pages/index.ts
- yarn.lock
> Create an internal validator FAQ page

- src/components/AppBar.tsx
- src/pages/Transactions/Keylist/ActionButton.tsx
- src/pages/Transactions/Keylist/index.tsx
- src/utils/envVars.ts
> WIP: display beacon explorer links, update network bubble styling

- src/pages/ConnectWallet/index.tsx
> add faucet for low balance users

- src/utils/envVars.ts
Update config defaults for Medalla eth2 testnet
> Update Medalla defaults

- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
> Correction to #146

- src/components/Alert.tsx
- src/pages/GenerateKeys/LinuxInstructions.tsx
- src/pages/GenerateKeys/MacInstructions.tsx
- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/GenerateKeys/WindowsInstructions.tsx
- src/pages/GenerateKeys/index.tsx
- src/styles/styledComponentsTheme.ts
updates Mac, Windows & Linux instuctions to meet new requiments outlined in #138
> Update generate keys instructions

- src/pages/GenerateKeys/Option2.tsx
Update the context and git clone command to make sure that the user is using the `master` branch.
> Make sure the user is using `master` branch

- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/GenerateKeys/index.tsx
- src/pages/ValidatorClients/Prysm.tsx
addresses 2nd and 3rd comments outlined [here](https://github.com/ethereum/eth2.0-deposit/issues/160).
> key generation UX edits

- src/pages/FAQ/index.jsx
addresses https://github.com/ethereum/eth2.0-deposit/issues/170
> Update FAQ (index.jsx)

- .env.template
- src/pages/Clients/Eth2/Lighthouse.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/Clients/Eth2/Prysm.tsx
- src/pages/Clients/Eth2/Teku.tsx
- src/utils/envVars.ts
Address #155 
Replace #190: We will have to change setting `REACT_APP_PRYSM_INSTALLATION_URL` when we have Prysm's Zinken installation guide.
> Make installation URLs to ENV vars

- .eslintrc.js
- src/Routes.tsx
- src/pages/Checklist/index.tsx
- src/pages/index.ts
> Adds Checklist page

- public/index.html
Adding in a meta tag to verify our Fortmatic account for production
> Fortmatic meta verification

- src/pages/SelectClient/index.tsx
addresses https://github.com/ethereum/eth2.0-deposit/issues/194
> Explain why you need to choose an eth1 client

- src/pages/SelectClient/index.tsx
> Fix SelectClient page: `==` -> `===`

- src/pages/Landing/Phases/index.tsx
> Remove reference to phase "3"

- src/components/AppBar.tsx
- src/pages/Checklist/index.tsx
Post merge QA
before:
after:
e.g.,
> Minor style adjustment

- .env.template
- src/pages/GenerateKeys/Option1.tsx
- src/utils/envVars.ts
PR feedback of #211
It ensures that the given URLs match `MIN_DEPOSIT_CLI_VERSION` version.
> Bump default `MIN_DEPOSIT_CLI_VERSION` to 0.4.1 and use envVars for the URLs

- src/components/AppBar.tsx
> Header styling updates

- src/pages/Checklist/index.tsx
> slight design tweaks to new checklist security items

- src/pages/Checklist/index.tsx
Fix #227
Port https://github.com/eth2-clients/user-experience/pull/7 content updates to the launchpad checklist.
To reviewers:
Feel free to push commits for a better CSS style if need.
> Add more security setting items

- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/utils/envVars.ts
Replace #252
Use `IS_MAINNET` and `ETH2_NETWORK_NAME` to generate
- `TICKER_NAME`
- `BEACONSCAN_URL`
- `BEACONCHAIN_URL`
> Simplify envVars

- src/pages/Checklist/index.tsx
Fix #257 
Thanks to @dactar for the report.
> Fix blockchain explorer links

- src/pages/Summary/index.tsx
- src/utils/envVars.ts
- Set `IS_MAINNET` to true if `REACT_APP_IS_MAINNET` is unset
- husky auto linter adjustment
> Set `IS_MAINNET` to true if `REACT_APP_IS_MAINNET` is unset

- src/pages/Clients/Eth1/OpenEthereum.tsx
Thank @austinfromboston for the report.
Close #262.
> Fix OpenEthereum URLs

- src/pages/Checklist/index.tsx
> Update Prysmatic Labs Discord link

- src/pages/Landing/TimelineMilestones.tsx
I guess we moved ahead... Therefore I changed the pictures.
> Updated Timeline Images to Phase 0

- public/index.html
- src/components/AppBar.tsx
- src/components/Button.tsx
- src/components/Footer.tsx
- src/components/Link.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/Checklist/index.tsx
- src/pages/Clients/Eth1/Besu.tsx
- src/pages/Clients/Eth1/Geth.tsx
- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Congratulations/index.tsx
- src/pages/FAQ/index.jsx
- src/pages/Landing/Hero.tsx
- src/pages/Landing/Introduction.tsx
- src/pages/Landing/NetworkStatus/index.tsx
- src/pages/Landing/SignupSteps/index.tsx
- src/pages/Landing/StakingRewards.tsx
- src/pages/Landing/StakingRewardsChart/index.tsx
- src/pages/Landing/Upgrades/UpgradeCard.tsx
- src/pages/Landing/Upgrades/index.tsx
- src/pages/NotFound.tsx
- src/pages/SelectClient/index.tsx
- src/pages/Summary/index.tsx
A PR for all content work associated with global elements and the landing page. Will try and segment commits as much as possible so it's clearer what's changed.
Can merge into main translations branch when approved.
> Global and landing page content changes

- src/Routes.tsx
- src/components/AppBar.tsx
- src/components/PageTemplate.tsx
- src/pages/Languages/index.tsx
- src/pages/index.ts
This PR adds a language page to the launchpad for when translations are complete.
> Adds language page

- .rescriptsrc.js
- package.json
- src/intl/en.json
- src/pages/FAQ/index.jsx
- src/pages/Languages/index.tsx
- yarn.lock
Spike to add text extraction for translations
> Support text extraction

- src/Routes.tsx
- src/intl/en.json
- src/pages/Languages/index.tsx
Extract copy from languages page for translations
> Translate languages page

- src/pages/Landing/Introduction.tsx
We've had a lot of confusion around whether staking makes you a miner in Eth2. This PR aims to combat this misconception.
> Validating =\ mining

- src/components/ImageSelectionBox.tsx
- src/components/SelectionBox.tsx
- src/components/WorkflowPage/WorkflowProgressBar.tsx
- src/intl/en.json
- src/pages/Clients/Eth1/Besu.tsx
- src/pages/Clients/Eth1/Geth.tsx
- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Clients/Eth1/OpenEthereum.tsx
- src/pages/Clients/Eth2/Lighthouse.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/Clients/Eth2/Prysm.tsx
- src/pages/Clients/Eth2/Teku.tsx
- src/pages/SelectClient/SelectClientSection.tsx
- src/pages/SelectClient/index.tsx
Content updates to the "Select client" part of the flow.
Still todo:
> Select client updates

- src/components/Button.tsx
- src/pages/Landing/NetworkStatus/index.tsx
- src/pages/Landing/StakingRewards.tsx
Removes references to "until threshold".
Adds simple context for the minimum threshold.
> Deposit threshold and staking rewards

- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/GenerateKeys/index.tsx
Content updates to the generate keys step
> Generate keys updates

- src/components/AppBar.tsx
- src/pages/Landing/Hero.tsx
- src/pages/Landing/index.tsx
Allows users to better access educational content when viewing on non-desktop devices.
Todo:
> Adds mobile menu and shortcut to languages

- src/pages/Checklist/index.tsx
- src/pages/FAQ/index.jsx
Copied over the tip from the Checklist page in case folks miss it or go to FAQ looking for support.
> Add Support section to FAQ

- src/Routes.tsx
- src/components/WorkflowPage/WorkflowProgressBar.tsx
- src/pages/UploadValidator/index.tsx
Reformatted page copy and error messages for translations.
> Upload validator content and error messages formatted for translations

- src/components/Footer.tsx
- src/components/Link.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/Checklist/index.tsx
- src/pages/Clients/Eth1/Besu.tsx
- src/pages/Clients/Eth1/Geth.tsx
- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Clients/Eth1/OpenEthereum.tsx
- src/pages/Clients/Eth2/Lighthouse.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/Clients/Eth2/Prysm.tsx
- src/pages/Clients/Eth2/Teku.tsx
- src/pages/ConnectWallet/MetamaskHardwareButton.tsx
- src/pages/ConnectWallet/index.tsx
- src/pages/FAQ/index.jsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/Landing/Introduction.tsx
- src/pages/Landing/NetworkStatus/index.tsx
- src/pages/Landing/StakingRewards.tsx
- src/pages/Landing/Upgrades/UpgradeCard.tsx
- src/pages/Landing/Upgrades/index.tsx
- src/pages/SelectClient/SelectClientSection.tsx
- src/pages/TermsOfService/index.tsx
- src/pages/Transactions/Keylist/ActionButton.tsx
- src/pages/UploadValidator/index.tsx
No need to explicitly pass the `external` prop each time.
> Refactor Link to calculate isExternal

- src/components/Link.tsx
@ryancreatescopy this fixes your button link issue from #320
> Only display external link arrows for text links

- src/components/Link.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/Checklist/index.tsx
- src/pages/Congratulations/ProgressBarInfo.tsx
- src/pages/Congratulations/index.tsx
- src/pages/ConnectWallet/index.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/Landing/NetworkStatus/index.tsx
- src/pages/Summary/index.tsx
- src/utils/envVars.ts
Refactored "Congratulations" page with `react-intl`
Added descriptions where it felt helpful
> Congratulations page refactor using FormattedMessage

- src/components/Link.tsx
- src/pages/ConnectWallet/MetamaskHardwareButton.tsx
- src/pages/FAQ/index.jsx
- src/pages/Summary/index.tsx
Set up summary page for translations
> Set up summary page for formattedMessage

- src/pages/Transactions/Keylist/ActionButton.tsx
- src/pages/Transactions/Keylist/Status.tsx
- src/pages/Transactions/Keylist/index.tsx
- src/pages/Transactions/index.tsx
- Consolidated transactions "confirm all tx" and key files table into one section
- Adjusted some language
- Set up for translations
Note: it's kind of hard to test all the different outcomes, would be worth going through together @samajammin @wackerow  v carefully.
> Set up transactions page for translations

- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/Clients/Eth2/Prysm.tsx
- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- src/pages/Landing/SignupSteps/Step.tsx
- src/pages/Landing/SignupSteps/index.tsx
- src/pages/SelectClient/SelectClientSection.tsx
- src/pages/SelectClient/index.tsx
- Refactored homepage steps
- Added "go offline" warning to generate keys step
- Moved Eth1 client explanation to within card
- Updated / fixed broken client docs links
> Some extra content improvements

- src/pages/Checklist/index.tsx
- Updated approximate Geth size
- Added recommendation to not wait on eth1 chain syncing
- Refactored Checklist to use `<FormattedMessage />` component and `formatMessage()`
- Provided descriptions whenever "values" attribute is used to assist translators. 
@samajammin Lemme know if this looks correct to prepare for crowdin
> Checklist refactor using FormattedMessage

- src/pages/Clients/Eth2/Lighthouse.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/Clients/Eth2/Prysm.tsx
- src/pages/Clients/Eth2/Teku.tsx
- Eth2 clients Teku, Nimbus, Prysm and Lighthouse pages refactored using `FormattedMessage` component
- Cleaned up some code strings
> Eth2 client pages refactored using FormattedMessage

- src/pages/Clients/Eth1/Besu.tsx
- src/pages/Clients/Eth1/Geth.tsx
- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Clients/Eth1/OpenEthereum.tsx
- Eth1 clients Basu, Nethermind, OpenEthereum, and Geth pages refactored using `FormattedMessage` component
> Eth1 client pages refactored using FormattedMessage 

- src/pages/FAQ/index.jsx
- FAQ page refactored using `FormattedMessage` component
> FAQ page refactored using FormattedMessage

- src/components/Footer.tsx
- src/pages/Phishing/index.tsx
- Small content tweaks to phishing page
- Added formattedMessage component
- Added link in footer to phishing page
Question: is it worth adding this to the main appbar?
> Added formattedMessage to phishing page

- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
- Refactored `GenerateKeys/Option1.tsx` and `GenerateKeys/Option2.tsx` to use `FormattedMessage` and `formatMessage()` to prepare for translations.
- Removed arrow from GitHub button link
- Tiny corrections/tweaks
> Generate keys (options 1 and 2) intl refactor

- src/intl/en.json
- src/pages/Clients/Eth1/Nethermind.tsx
- src/pages/Congratulations/index.tsx
- src/pages/ConnectWallet/index.tsx
- src/pages/GenerateKeys/Option2.tsx
> Translations cleanup

- src/components/Link.tsx
- src/pages/Acknowledgements/AcknowledgementProgressTracker/index.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/Checklist/index.tsx
- src/pages/Clients/Eth1/Nethermind.tsx
- src/store/reducers/acknowledgementReducer.ts
Restructured checklist
@samajammin @ryancreatescopy Take a look at this and let me know what you think of the changes. Modeled after Figma notes.
> Checklist upgrade

- src/components/Link.tsx
- src/components/LocalizedRouter.tsx
- src/intl/de.json
- src/intl/fr.json
- src/intl/index.ts
- src/pages/Languages/index.tsx
Remove placeholder `$lang.json` files & update Language page to only display currently supported languages (i.e. English)
> Update language support to English only

- src/components/Footer.tsx
- src/pages/Acknowledgements/pageContent.tsx
- src/pages/Checklist/index.tsx
- src/pages/Clients/Eth2/Nimbus.tsx
- src/pages/ConnectWallet/index.tsx
- src/pages/FAQ/index.jsx
- src/pages/Landing/Upgrades/index.tsx
- src/pages/Transactions/Keylist/ActionButton.tsx
Some tweaks and fixes as we QA the translations branch.
> Final final final(?) content pr into translations

- package.json
- src/intl/compiled/en.json
- src/intl/en.json
- src/intl/index.ts
- src/pages/Checklist/index.tsx
Add `compile` script to properly compile & import translation JSON files. 
This should resolve the host of console errors we've been seeing.
See https://github.com/formatjs/formatjs/issues/2589 for more context
> Compile translations

- README.md
- src/pages/GenerateKeys/Option1.tsx
- src/pages/GenerateKeys/Option2.tsx
Just a couple of minor typo/capitalization fixes.
> Fix capitalization

- src/components/AppBar.tsx
Minor copy change. Felt this makes it a bit clearer. @ryancreatescopy curious to hear your thoughts.
> Clarify network message

- src/pages/ConnectWallet/index.tsx
Subscribe to new blocks & update account balance if it changed
> Poll account balance

- public/index.html
Update OG image to full size image & full URL of image path.
https://ogp.me/
> Update og:image [Fixes #373]

- src/pages/TopUp/components/ValidatorTable.tsx
- src/pages/Transactions/Keylist/ActionButton.tsx
The URLs to beaconcha.in validator page was wrong.
Add resource name `validator/`.
> Fix links to beaconcha.in validator page

- src/components/AppBar.tsx
- src/components/Footer.tsx
- src/pages/Congratulations/index.tsx
- src/pages/Landing/Hero.tsx
- src/pages/Landing/NetworkStatus/index.tsx
- src/pages/Landing/SignupSteps/index.tsx
- src/pages/Landing/index.tsx
- src/pages/TopUp/components/TopUpTransactionModal.tsx
- src/pages/Transactions/index.tsx
- Fixes double external link arrow showing for Etherscan on Top-Up modal
- Fixes "Top Up" wrapping on top nav bar
- Fixes anchor links extending beyond buttons on homepage
- Makes "Confirm deposits (1)" show "Confirm deposit" if singular
Fixes most of #378, but does not address `REACT_APP_INFURA_PROJECT_ID` issue
> Translations audit fixes

- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/Acknowledgements/pageContent.tsx
- Adds three missing strings to translations
- New `en.json` has been uploaded to Crowdin
> Adds intl for BoldCaps strings [Fixes #391]

- src/pages/Landing/Upgrades/index.tsx
> Fix eth2 docking link

- src/intl/compiled/en.json
- src/intl/compiled/pl.json
- src/intl/en.json
- src/intl/index.ts
- src/pages/Languages/index.tsx
> Adds Polish translations

- README.md
Add a section about the Launchpad translation initiative to the readme, with instructions for getting involved as a translator.
Related issue:
#412
> Add section about translations to readme

- src/pages/Checklist/index.tsx
- Fixes an incorrect link for the Teku JWT documentation
> Patch: Teku JWT docs link

- src/components/WithdrawalsTabComparison.tsx
- src/pages/Withdrawals/index.tsx
Branch off `withdrawals` PR with content rearranged per Figma suggestions
Preview link: https://deploy-preview-583--serene-carson-3331d5.netlify.app/en/withdrawals
For preview purposes, **do not merge**
> [WIP] Withdrawals modified

- src/components/AppBar.tsx
- src/components/WithdrawalCredentials.tsx
- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/Withdrawals/index.tsx
Updating `shapella` branch with latest from `withdrawals` branch progress
> `withdrawals` -> `shapella` deploy

- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/Withdrawals/index.tsx
- Adds a note about the inability to re-stake to an already-exited validator
> Add note on re-staking to withdrawals content

- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/BtecGuide/index.tsx
- Adds a link at the end of the BTEC guide providing a GUI option for users to upload their signed BTEC message using the new [Beaconcha.in broadcast tool](https://mainnet.beaconcha.in/tools/broadcast)
> [feat] link BTEC to beaconcha.in broadcast tool

- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/Withdrawals/index.tsx
> Add missing word (blocks)

- src/components/WithdrawalsTabComparison.tsx
- src/intl/compiled/en.json
- src/intl/en.json
- src/pages/Withdrawals/index.tsx
- Add a mention to Wagyu Key Gen being able to create a key change
- Remove mention to removed advanced section
> Improved Wagyu Ken Gen usage in withdrawals page

- src/pages/Checklist/index.tsx
Our documentation site has been updated. This PR updates checklist links.
There might be other links to fix.
> Fix teku checklist doc links

- src/pages/ConnectWallet/index.tsx
Fixes the positioning of components within the `/upload-deposit-data` and `/connect-wallet` steps
- Removes the `absolute` positioning being used on the `WalletConnectedContainer` component which was causing this to sit on top of the `ButtonRow` at certain screen sizes.
- Adjusts some condition logic to hide/show needed components based on whether a wallet is connected or not
https://deploy-preview-669--dapper-rolypoly-9814ad.netlify.app/
- Fixes #659
> Patch component positioning [Fixes #659]

- src/intl/compiled/pl.json
- src/intl/compiled/zh.json
Fixes mistranslations of Ethereum in Chinese Simplified and Polish
> Fix mistranslations of Ethereum

- src/pages/Checklist/index.tsx
- src/pages/Clients/Execution/Nethermind.tsx
Updated obsolete links to Nethermind docs and revised outdated instructions.
> Update Nethermind page

- src/pages/TopUp/index.tsx
> top-up page proofreading
