src/pages/GenerateKeys/LinuxInstructions.tsx
src/pages/GenerateKeys/MacInstructions.tsx

Fixes #60 by updating the instructions for the CLI changes. 
- adds in additional step running `setup.py`
- changes from `src/deposit.py` to `cli/deposit.py`
This is a temporary fix to allow early users to complete the current flow. When further changes to the CLI are made we can update these instructions and update #64

Update instructions for CLI changes

---

src/pages/GenerateKeys/LinuxInstructions.tsx
src/pages/GenerateKeys/MacInstructions.tsx
src/pages/GenerateKeys/WindowsInstructions.tsx

Pending on https://github.com/ethereum/eth2.0-deposit-cli/pull/19. We can use the same script for all OSs.
1. Update the commands.
2. Note that `deposit-cli` requires python3.7+.

Update the instruction commands: use deposit script

---

src/pages/UploadValidator/validateDepositKey.ts
src/store/reducers/depositFileReducer.ts
src/utils/verifySignature.ts

Different chains require different `fork_versions`. These need to be coordinated between the CLI and the launchpad.
Required for merging ethereum/eth2.0-deposit-cli/pull/32

Pulls fork_version from deposit_data.json

---

.eslintrc.js
package.json
src/pages/Transactions/transactionUtils.tsx
src/pages/UploadValidator/validateDepositKey.ts
src/store/reducers/depositFileReducer.ts
src/utils/SSZ.ts
src/utils/envVars.ts
src/utils/verifySignature.ts
yarn.lock

At the moment, the signature is verified against the root provided by the deposit-cli. This is unsafe if the root is not correctly calculated, the message that is signed could be incorrect.
In addition to the above, the deposit data json checker was brittle.
This addresses the above by using @chainsafe/ssz to verify the root as well as implementing the signature verification methods from the eth2-spec.
* Closes #61 
* Resolves ethereum/eth2.0-deposit-cli/issues/23 (Root re-verification)
* Required for ethereum/eth2.0-deposit-cli/pull/32 (`fork_version `)
@hwwhww, I'd like your review for the root checking & signature verification
@Battenfield, Please can you check my typescript.

Verifies SSZ encoding with @chainsafe/ssz

---

.eslintrc.js
package.json
src/contractAbi.ts
src/pages/UploadValidator/validateDepositKey.ts
src/utils/SSZ.ts
src/utils/envVars.ts
yarn.lock

#83 Added SSZ verification of the roots in the deposit-json file. Unfortunately, as was presented in #87, this broke compatibility with some browsers (those that do not support ES2020 yet).
@wemeetagain pushed some changes to @chainsafe/SSZ and its dependancies so that `BigInt`s are not called while calculating hash-tree-roots for sufficiently small ints.
This PR bumps the SSZ version, changes the local types, and performs range checks on the deposit amount.

Fixes #87: BigInt dependency that caused browser compatibility issues

---

src/components/PageTemplate.tsx

- Adds in `<PageTemplate/>` which can be used for informational pages

Page template for new non-workflow pages

---

src/pages/Acknowledgements/pageContent.tsx
src/pages/FAQ/index.jsx
src/pages/Landing/Introduction.tsx
src/pages/Phishing/index.tsx

Changes wording to emphasise that eth2 is an upgrade to the consensus of Ethereum, not a replacement of "eth1".

Remove all references to "eth1"

---

src/pages/Landing/NetworkStatus/index.tsx

The text of the Network status graphs is rather unclear as to what numbers are what (see picture below), this PR clarifies that.

Clarifies numbers on network status

---

src/pages/ValidatorClients/Prysm.tsx

Hi all,
This pull requests updates the Prysm page in the eth2 launchpad to point to our new docs https://docs.prylabs.network/docs/testnet/medalla.

Add Updated Links to Prysm's Documentation Post-Launchpad

---

src/pages/Landing/Hero.tsx

as per a conversation with danny, the inability to immediately withdraw or transfer means the term payouts may be misleading.

Update Hero.tsx (change payouts to rewards)

---

src/pages/FAQ/index.jsx
src/pages/UploadValidator/index.tsx
src/utils/envVars.ts

* Ignore the apostrophe changes, those are an artifact of previous changes
* If the default `GENESIS_FORK_VERSION` was being overridden by `process.env.REACT_APP_GENESIS_FORK_VERSION`, then it was done as a string, not a Buffer (bytes). This fixes that.

GENESIS_FORK_VERSION as bytes

---

src/pages/Transactions/Keylist/ActionButton.tsx
src/pages/Transactions/index.tsx
src/pages/Transactions/transactionUtils.tsx

Solves double deposit issue explained in #183. In the change from offering one-at-a-time deposit processing to multiple deposits via the "Initiate All Deposits" button, the status of a transaction was no longer updated to reflect that the TX was `PENDING`. This PR solves that as well as cleans up the `handleMultipleTransactions` recursion.

[Urgent] Update TX status to PENDING in `handleMultipleTransactions`

---

src/pages/Congratulations/index.tsx

Eth2 Client pages are now reachable from the Navbar and the client cards are on the Checklist page.

Remove client cards from congrats page

---

src/pages/Transactions/Keylist/ActionButton.tsx
src/utils/envVars.ts

Alethio links are not working as they were previously for deposit transactions. Removing them as Etherescan is sufficient for Eth 1.

Remove Alethio links and vars

---

src/pages/GenerateKeys/Option1.tsx
src/pages/GenerateKeys/Option2.tsx

**Description**
On the **Generate Keys** page, the two options both had `testnet` hardcoded into the string after the network name. To maintain flexibility, my fix includes a conditional, where if the network name (lowercased) is anything other than 'mainnet' then ' testnet' will be added, otherwise nothing will be added. 
**Related issue**
#242 
(My first PR to this repo... let me know if there are issues, and of course, feel free to ignore 😉)

Removes 'testnet' when network is 'mainnet' [Fixes #242]

---

src/pages/UploadValidator/index.tsx
src/pages/UploadValidator/validateDepositKey.ts
src/store/reducers/depositFileReducer.ts

We've been hitting rate limits (10/minute) on the beaconcha.in API because we are making 1 API call per validator. This PR makes use of the API's ability to respond to multiple simultaneous requests so that only 1 request is made to the API.

Makes 1 call to beaconchain API for all validators

---

src/pages/Checklist/index.tsx

The "at least 140 GB SSD to run geth fast" may be outdated.
Changing it to 290 GB.
---
Thank @nonsense for [finding this issue](https://discord.com/channels/595666850260713488/598292067260825641/778352824114217003).
> A new node takes around 290 GB... and only grows from there on
Also thank @michaelsproul for [confirming the number](https://discord.com/channels/595666850260713488/598292067260825641/778472799324602378):
> I recently fast synced Geth from scratch and it's using 287 GB (122 GB hot + 165 GB freezer)

Fix minimum geth fast sync disk size

---

src/pages/GenerateKeys/Option1.tsx

Some shells (notably Powershell on Windows) require a leading `.\` when executing something from the current directory.  This also ensures that if the user has some globally installed `deposit` binary on their machine that won't be used and only the `deposit` file in the current directory will be or the command will fail (a good thing in this case).

Makes deposit command compatible with all shells.

---

src/pages/Transactions/Keylist/ActionButton.tsx
src/pages/Transactions/transactionUtils.tsx

If a user takes too long to sign a deposit on their HW wallet, or they accidentally reject it on their HW wallet, Metamask returns a different error, this handles those cases. Addresses #279

Allow retry on failed deposits

---

src/pages/Checklist/index.tsx

Small typo correction on the checklist page (`are are`): 
Simple correction.

Removed duplicated word typo

---

src/components/WorkflowPage/WorkflowPageTemplate.tsx
src/components/WorkflowPage/WorkflowProgressBar.tsx
src/pages/Acknowledgements/AcknowledgementProgressTracker/index.tsx
src/pages/Acknowledgements/index.tsx
src/pages/Acknowledgements/pageContent.tsx
src/store/reducers/acknowledgementReducer.ts

This PR addresses the main confirmations flow (with all the warnings and "I accept" buttons) when you follow the CTA to become a validator. 
Major updates include
- Giving the terminal its own step: You need to be able to use a terminal to run a validator
- Relabelling
- Adding a subtitle that explains the purpose of the section

Overview section

---

src/components/LocalizedRouter.tsx
src/pages/Languages/index.tsx

- Prevents `/en` from redirecting to `/en/en`
- If no two-letter language code, will default to `/en/`
- If two-letter code not supported, will redirect to `/en/lanagues` to select a supported language
- Cleaned up a couple console warnings (.map key/idx, and `<text>` -> `<p>`)

Language path adjustments

---

package.json
src/intl/en.json
src/pages/Clients/Eth2/Teku.tsx

@ryancreatescopy @wackerow @sorumfactory - good news. The `react-intl` supports automatic text extraction & can output into a [JSON format that plays nice with Crowdin](https://formatjs.io/docs/getting-started/message-extraction#translation-management-system-tms-integration).
The JSON format looks like this:
```
"25suT4": {
"description": "The {semicolon} and {colon} variables refer to the keyboard characters ';' and ':'.",
"message": "The path separator is operating system dependent, and should be {semicolon} in Windows rather than {colon}."
},
```
I've tested this out by uploading our `en.json` file into a test Crowdin project:
https://crowdin.com/project/eth2-launchpad-test
Now we can use variables and provide descriptions of the phrases directly in the code, e.g. in `Teku.txs`:
``` …
```

Add Crowdin text extraction format

---

src/components/AppBar.tsx
src/components/Dot.tsx
src/pages/ConnectWallet/MetamaskHardwareButton.tsx
src/pages/ConnectWallet/WalletButton.tsx
src/pages/ConnectWallet/WalletDisconnected.tsx
src/pages/ConnectWallet/WrongNetwork.tsx
src/pages/ConnectWallet/index.tsx

This step focusses on the user choosing a wallet and getting feedback from the app whether they're on the correct network and they have the required balance for the number of validators they want to run.
Problems fixed:
- previous design relied on color to indicate whether the network was correct. This is inaccessible so added an icon to show status.
- it was confusing that the dot would display green (to demo that the network was correct) even if you couldn't proceed because of an insufficient balance. This is now split into two separate checks.
- Added error messages inline to wallet balance and network statuses
- disabled the continue step if balance is insufficient (I assume this was accidentally left out before – please correct me if this is incorrect)
Todo:

Connect wallet updates

---

src/pages/Acknowledgements/index.tsx
src/pages/Acknowledgements/pageContent.tsx
src/pages/GenerateKeys/index.tsx

- Rearranged the "Key management" overview step copy to fit a little nicer and remove some redundancy. This prevents the "Continue" button from shifting downward too much during this flow.
- Also adds an instance of intl to acknowledgement index page

Key management overview step trimming

---

src/components/AppBar.tsx
src/pages/Landing/Hero.tsx
src/utils/envVars.ts

Makes it easier to switch between mainnet and testnet launchpads. 
App content advises users to practice on testnets, so we should make it easier to switch. This PR turns the launchpad network indicator into a button.
Created this PR before we merged a bunch of stuff into `translations` so expect conflicts ;/
Fixes #322

Adds network switch [#322]

---

src/components/WorkflowPage/WorkflowPageTemplate.tsx

- Intl upgrades altered the URL path being checked when deciding which active step the user is on
- This PR adds logic to check for the language locale and remove it from the path before checking it against the enumerated step names, and thus restores the conditional color formatting for the active item on the workflow nav bar. 
(@samajammin @ryancreatescopy)

Restores active workflow path highlighting

---

src/components/Link.tsx
src/pages/Landing/Upgrades/index.tsx

- Added logic to check for links going to `ethereum.org` pages (no sub-domains)
- Checks if link matches users current locale / language selection
- If it does, link passes unchanged. If it doesn't match or doesn't have a language path, the users current locale is injected to the link.

Links to ethereum.org maintain users locale

---

src/pages/FAQ/index.jsx

"What happens I lose my signing key" -> "What happens *if* I lose my signing key"

Fix typo in FAQ

---

src/components/Link.tsx

Fix bug from #360 where all non-ethereum.org external links were set to empty string.

Fix external links

---

src/components/WorkflowPage/WorkflowProgressBar.tsx

- Trims the horizontal margin on workflow nav items by half (20px -> 10px)
- Prevents wrapping of workflow nav item names above 1080px screen size
Bug ("Transaction" wrapping to new line):
Fix:

Trims margin on workflow nav items

---

src/pages/Acknowledgements/pageContent.tsx

During the acknowledgements step, if the user clicks the internal link and then goes back, they will return to Step 1. For better UX, the links should be opened on new tabs.
Add `shouldOpenNewTab={true}` to these links.

Use _blank link during the acknowledgements step

---

src/pages/Checklist/index.tsx

The string values passed to `FormattedDate` aren't parsed into valid Dates and is showing "Invalid Date" on the Checklist page.

Fix Checklist dates

---

src/components/AppBar.tsx

Minor style tweak - unifies margin of "Top Up" nav link with the rest.
Context: we tightened the margins (https://github.com/ethereum/eth2.0-deposit/commit/1d0b6d6673e29a0279c04fdc8a36e18ba7999d92) but must have missed updating the Top Up link when we added that (https://github.com/ethereum/eth2.0-deposit/pull/291)

Update top up link margins

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/FAQ/index.jsx

In that next deposit-cli release, https://github.com/ethereum/eth2.0-deposit-cli/pull/195 will introduce a new withdrawal credentials format - Eth1 address withdrawal. This PR adds some description about what are withdrawal credentials and this new feature.
Note that do not merge this PR before the next deposit-cli release.

Add "withdrawal credentials" section to FAQ

---

src/pages/GenerateKeys/Option2.tsx

At this moment, the Launchpad site is ready for translations, but the translated `--chain` CLI command shown to users is currently not a live feature in the actual deposit CLI tool. 
This adds a boolean conditional to skip translating this for now, and to just leave `--chain` in English, which the deposit CLI will accept without issues.

CLI flag translation prevention

---

README.md

Reading "This Launchpad is in active development for testnet" gave me the impression that we're saying it's not ready for use on Mainnet. I don't think this is the message we want to send, given this app is used on Mainnet.
Am I misunderstanding this? Otherwise I think we should remove this statement.

Remove status

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Checklist/index.tsx
src/pages/FAQ/index.jsx

- Adds links for `execution layer` and `consensus layer` terms on the FAQ page
- Adds links for `execution client` and `consensus client` terms on the checklist page
- `yarn extract && yarn compile` has been run
https://www.notion.so/efdn/Add-links-to-glossary-terms-a7ea3cf7feff4e05a69d15ce28a81204

Adds links to e.org glossary terms

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Clients/Consensus/Prysm.tsx

Like I mentioned in #427, I think it is important to inform users of the risks of running a (super-) majority consensus client.
I added a simple disclaimer if the user chooses Prysm and a link to the Ethereum docs about client diversity.
The warning is hardcoded in the Prysm markup which means it has to be manually moved if another client gets majority in the future, but I don't see this happening anytime soon.
I don't know if this is even something you want on the website in this form or another but I'm open for suggestions.

Add client diversity warning if user selects Prysm

---

src/components/AppBar.tsx
src/intl/compiled/en.json
src/intl/en.json
src/pages/ConnectWallet/WrongNetwork.tsx
src/pages/ConnectWallet/index.tsx
src/pages/ConnectWallet/web3Utils.ts
src/pages/Summary/index.tsx
src/pages/TopUp/components/WalletConnectModal.tsx
src/pages/Transactions/index.tsx

1. Using German is config made us have to use `NetworkChainId['Göerli']`. As we are adding Ropsten and other EL testnets, it would be easier in parameterization if we can just use English "Goerli".
2. It turns out `Göerli` is a typo and it should have been `Görli`. 😅  Let's just use `Goerli`.

Use English "Goerli" instead of typo German "Göerli"

---

src/pages/FAQ/index.jsx

Adds `inline` and `primary` props where needed to FAQ links
None filed, but note example here:
With fix:

FAQ link patch

---

src/components/NakedButton.tsx
src/hooks/useKeyPress.ts
src/pages/TopUp/components/ValidatorTable.tsx
src/pages/TopUp/components/WalletConnectModal.tsx
src/pages/TopUp/index.tsx
src/static/close.svg

- Adds closing `X` to modal pop-up on `/top-up` page
- Adds "Connect wallet" button to same page if user has not connected, and has exited the modal
[Fixes #383]

Add top-up modal escape [Fixes #383]

---

src/components/Link.tsx

Changes Link component to `font-weight: 400;` always, and instead dims to `opacity: 0.8;` on hover.
[Fixes #501]

Link hover styling change [Fixes #501]

---

src/components/ClientDiversityWarning.tsx
src/intl/compiled/en.json
src/intl/en.json
src/pages/Clients/Consensus/Prysm.tsx
src/pages/Clients/Execution/Geth.tsx

- Extracts the component being displayed on the Prysm page, and makes it more generalizable.
- Allows passing "children" to the component to customize the message being displayed where it is used.
- Adjusted copy for Prysm warning (no longer being used by true majority, but still more popular and over 33%)
- Added component to Geth page with similar warning about being over 66%. 
- Added link to clientdiversity.org for users to check the latest numbers
Geth preview: https://deploy-preview-512--serene-carson-3331d5.netlify.app/en/geth
- #508

Extract and re-use ClientDiversityWarning [Fixes #508]

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/MergeReadiness/index.tsx

- Updates design of /merge-readiness page to include notices about waiting on certain tasks until the TTD has been announced and included in client updates.
- Design changes include dimming of the two tasks that should not yet be performed and disabling the checklist buttons.
- Adds "timing" note to the task cards
- #511 
https://deploy-preview-514--serene-carson-3331d5.netlify.app/en/merge-readiness

Await TTD notice added for MergeReadiness [Fixes #511]

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/MergeReadiness/index.tsx

- Per suggestion from @konopkja, added action words to the CTAs on the Merge Readiness page

Add actions words for Merge Readiness CTAs

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/SelectClient/SelectClientSection.tsx

- Adds a note on the client selection page to remind users that they should make sure their clients are fully syncs before submitting their staking deposit. 
Suggested [here](https://hackmd.io/@prysmaticlabs/validator-ux)

Add sync note to client selection

---

src/pages/Landing/Upgrades/index.tsx

- Noticed [we're translating this string elsewhere](https://github.com/ethereum/staking-launchpad/blob/b65c9e38fd59c78bfeb84f4f0b8846e270a8caea/src/components/MergeNotification.tsx#L19), but not here.

Translate "merge readiness checklist" on upgrades page

---

src/components/AppBar.tsx
src/hooks/useIntlNetworkName.tsx
src/intl/compiled/en.json
src/intl/en.json
src/pages/Checklist/index.tsx
src/pages/Congratulations/index.tsx
src/pages/ConnectWallet/WalletDisconnected.tsx
src/pages/ConnectWallet/WrongNetwork.tsx
src/pages/ConnectWallet/index.tsx
src/pages/FAQ/index.jsx
src/pages/GenerateKeys/Option1.tsx
src/pages/GenerateKeys/Option2.tsx
src/pages/GenerateKeys/Option3.tsx
src/pages/Landing/Hero.tsx
src/pages/Landing/SignupSteps/index.tsx
src/pages/Landing/Upgrades/index.tsx
src/pages/MergeReadiness/index.tsx
src/pages/SelectClient/index.tsx
src/pages/TopUp/components/WalletConnectModal.tsx
src/pages/Transactions/Keylist/index.tsx
src/pages/UploadValidator/index.tsx
src/utils/envVars.ts

Fixes issue where intl variables used within `FormatMessage` component were not always set up for translation themselves.
example:
```ts
// Incorrect, as "not" does not get translated
values={{ not: <em>not</em> }}
// Corrected to:
values={{
not: (
<em>
<FormattedMessage defaultMessage="not" />
</em>
),
}}
```
- Extracts remaining strings, including "Mainnet" and "____ testnet" for translation.
- Also capitalized "Mainnet" and the testnet names for consistency
Note: There are some CLI variables such as `--num_validators` and `--chain` that are currently being translated. @CarlBeek Want to confirm that this is aligned with the `staking-deposit-cli` script.

Add translation support for nested strings

---

README.md

- Adds note about testnet (`master`) vs Mainnet (`mainnet`) deployment branches to the `README.md`
[Closes #525]

Update README with deployment branch info [Closes #525]

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/MergeReadiness/index.tsx

Draft of updates to the Merge Readiness Checklist page. Flips the TTD switch to notify node operators that it is now time to ensure their nodes are fully ready for The Merge.
- Removes "pending" fields and disabled appearance of some cards
- Removes warnings that this is only for the testnet at this time
- Adds note to make sure clients are up-to-date with a merge-ready release
- Adds Goeli links to #TestingTheMerge section, noting this was the final public testnet to undergo the merge.
- Updated wording on this section to take out ability to test _before or going through the merge_ at this point.
- Removed broken tutorial link

Update merge readiness checklist for ttd

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/MergeReadiness/index.tsx

Adds a link to the blog post announcing Mainnet TTD on the Merge Readiness page in the initial alert box.

Add link to mainnet TTD blog announcement

---

src/pages/Clients/Consensus/Lighthouse.tsx

Heyo :wave: 
The Lighthouse blog has moved from `lighthouse.sigmaprime.io` to `lighthouse-blog.sigmaprime.io`.
I believe this PR makes the appropriate change, however I'm not so familiar with this code-base so some extra eyes would be appreciated :pray:

Update Lighthouse link

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/MergeReadiness/index.tsx

The last update to the Merge Readiness page included the TTD and estimated date for Mainnet merge, but did not include a note about the timing of the required Bellatrix upgrade set to occur for the Beacon Chain at epoch 144896. 
- Adds note about upgrading before Bellatrix
- Adds intl support for date/time formatting so these display appropriately in all locales.

Adds Bellatrix date warning

---

netlify.toml

- Creates `netlify.toml` (git tracked)
- Initializes with production, deploy-preview, branch-deploy and dev context to add `NODE_VERSION` environment var
- ~~Set node version to `16.15.0`, currently latest `stable` release~~
- Set node version to `14.19.2`\* (currently using `10.24.1`
\* Attempted to use v16 and [the build failed](https://app.netlify.com/sites/serene-carson-3331d5/deploys/63115a1b86c7640008e940af). We could look into this separately, but v14 is working which is what is required for #543 to pass.

Create netlify.toml, update node version

---

netlify.toml

Remove double `environment` nesting
```
[context.dev.environment]
environment = { NODE_VERSION = "14.19.2" }
```
This looks like it's resulting in `{ environment: {environment: { NODE_VERSION = "..." } } }`
Changed to:
```
[context.dev.environment]
NODE_VERSION = "14.19.2"
```
Clean up remaining items to match similar syntax pattern

Fix netlify toml syntax

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Checklist/index.tsx

Small copy change, LMK what you think @wackerow.
> All stakers must run a pair of both an execution and consensus client
This read to me like stakers must run a pair of each, i.e. 4 clients total.

Tweak copy to clarify client count

---

src/pages/ConnectWallet/WalletButton.tsx

Atm when one of tiles is disabled it still show `pointer` cursor while hovering on the text part.
Before fix:
After fix:

fix: use correct hover state for disabled tile

---

src/pages/SelectClient/SelectClientSection.tsx

- Evens out the visual display of the 4 EL clients and 5 CL clients on the select client pages
- 4 cards fit nicely on desktop, but 5 causes one to wrap. This add logic to put a max-width if there are >4 clients (CL clients) so it wraps after the third card instead
Noted in #586

Wrap client cards early if over four count

---

src/components/AppBar.tsx

Lodestar recently added to list of CL clients. The link was added to the desktop version but was missed in the mobile version.
- Adds Lodestar to mobile client menu
- Re-establish alphabetical order of clients in both menus

Add Lodestar to mobile client menu

---

src/pages/TopUp/index.tsx

Merge requested: `fix-top-up-one-deposit` <- `fix-top-up-one-deposit-refactor`
Following up on @hwwhww's PR #592, realized we could do a fair amount to clean up the fetching logic being performed on this component. Given I overhauled this function, figured I would post as a separate PR instead of as a suggestion on #592, or just committing directly to that branch.
- Switches to async/await syntax
- Uses `new URL()` objects to build dependable URL link
- Uses try/catch/finally block with guard clauses for error handling
These changes help remove the function chaining and nesting of code, and should improve readability and reliability.
Additionally, this cleans up the expected return values for the data we're fetching.
- The first call is fetching all pubKeys for a given eth1 address, and …

Top up data fetching refactor

---

src/pages/TopUp/index.tsx
src/pages/TopUp/types.ts

It was reported by @barnabasbusa.
The case is: if the user has only made **one** deposit before, our API response phaser would break. But if the user has made multiple deposits, it's alright.
Test case:
- The EL address has made only one deposit: https://zhejiang.beaconcha.in/api/v1/validator/eth1/0xF9dBc5fc75b5802916C66dae672e0aa124EDcD3e
- Error: it would go all-blank page once I connect the wallet. 
- `validators.map` TypeError: a.map is not a function at ValidatorTable.tsx:123:23
- The EL address has made multiple deposits: https://zhejiang.beaconcha.in/api/v1/validator/eth1/0xED6ee41b4Eee71Cc179683C3b90eFe20A1744D44
- This is all good. 
- Rename `BeaconChainValidatorResponse` to `BeaconChainValidatorEth1Deposit` because it was really confusing with `BeaconChainValidator`
- Accept …

Fix top-up where the EL address has only made one deposit 

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Acknowledgements/pageContent.tsx
src/pages/Checklist/index.tsx
src/pages/FAQ/index.jsx
src/pages/GenerateKeys/Option1.tsx
src/pages/Withdrawals/index.tsx

After adding the staking withdrawals page in #580, this PR addresses the remainder of the website by finding outdated content related to withdrawals and updating with the latest information.
This content is intended to be phrased with Shanghai/Capella still in the future, with noted timing of Q1/Q2 2023. There will be a PR to follow for _post_-Shanghai updates, which will then rephrase content once the upgrade has officially gone live.
- Updates deposit wizard acknowledgments copy
- Updates FAQ copy
- Couple small content patches on `/withdrawals` page
- Patches trailing `0` that was inappropriately rendering when user does not include a withdrawal address
- #577

Pre-Shanghai content cleanup

---

src/components/WithdrawalCredentials.tsx

Recent change to beaconcha.in API endpoint returns either an object or an array of objects, depending on the network being utilized.
This surfaced on the Zhejiang Withdrawals page in the credentials check widget, where the responses were no longer being parsed properly.
PR checks for `.length` property of `data` to differentiate between and object and an array, then parses out the first item in the case of an array.
Issue:
Patch:

[Patch] check for array type on beaconcha.in response

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/BtecGuide/index.tsx
src/pages/Withdrawals/index.tsx

- Extracts strings that were missed for translation
- Couple small copy tweaks for clarity in context of translations
- For example: adding "signed BLS-to-execution-change" (to be translated) before the untranslated variable name `SignedBLSToExecutionChange` is shown, so it reads properly in other languages
- Extracts placeholder text in BTEC walkthrough for translation
- For example "<YOUR MNEMONIC>" will now get translated instead of remaining in English

Extract missing strings for translation

---

src/pages/Checklist/index.tsx
src/pages/Congratulations/index.tsx
src/pages/FAQ/index.jsx

The old discord.io link has been broken for a few days now. This will fix it.

Fix EthStaker Discord invite link

---

src/pages/Clients/Execution/Besu.tsx

update dead links on the launchpad. Besu recently changed some documentation formats that caused this issue.

Update dead links for besu in launchpad

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Transactions/Keylist/ActionButton.tsx
src/pages/Transactions/index.tsx
src/pages/Transactions/transactionUtils.tsx
src/store/actions/depositFileActions.ts

When a user attempts to perform a deposit with a Ledger device, if **Blind Signing** and **Debug Data** is not enabled, the transaction will fail with seemingly no reason. This has been a problem for years and still people ask about it on the EthStaker discord. Though this issue may be resolved by updating the web3-react library from v6 to v8, a brief attempt at doing so resulted in dependency hell and would be quite a drastic change for this one small issue. I had a quick chat with @wackerow about this and we agreed an error message is the best approach. 
The error message will appear if either **Blind Signing** or **Debug Data** are disabled or, sadly, if the user simply rejects from the Ledger device. We have no way to differentiate but I feel the benefit of the guidance outweighs the …

Add error message for user when ledger fails when attempting to sign

---

src/pages/UploadValidator/index.tsx

compare fork version hex strings

---

.env.holesky
.env.template
package.json
src/pages/UploadValidator/validateDepositKey.ts
src/utils/envVars.ts
yarn.lock

When generating a deposit with the [staking-deposit-cli](https://github.com/ethereum/staking-deposit-cli), the resulting deposit file will contain a cli version: `deposit_cli_version`. The launchpad currently verifies this value is above a certain threshold defined in the env file, 2.7.0. 
There are two problems:
- If this check fails, the resulting error presented to the user says there is a problem with the network
- This makes it difficult for multiple tools to exist
To get around these two issues, this PR removes the version check entirely.
As a side effect, `compare-version` is no longer a direct dependency as this was the only location where it it is used but it is still a dependency of `husky`

Removing cli version checker

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/PartialWithdraw.tsx

The pre-commit hook rearranged the intl json file content for some reason.
This should fix the partial withdrawal implementation.

fix: added user partial withdrawal transaction code

---

src/pages/Actions/components/ValidatorActions.tsx
src/pages/Actions/components/ValidatorDetails.tsx
src/pages/Actions/index.tsx
src/pages/Actions/types.ts

Centralized the validator type logic when calling the API to be able to utilize an enum.

Updating validator credential prefix logic to use enum

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/TopUp.tsx
src/pages/Actions/components/ValidatorActions.tsx
src/pages/Actions/components/ValidatorDetails.tsx
src/pages/Actions/index.tsx
src/pages/Actions/types.ts

Duplicates logic from `TopupPage` and `PartialWithdraw` to allow a user to send funds to their validator. 
This is branched off of #728

Add "Top Up" option to validator actions

---

src/pages/Actions/utils.ts
src/utils/envVars.ts

Fixes bug causing browsers to freeze pre-Pectra-fork since these contracts are returning the 2^255 EXCESS_INHIBITOR value when fetching the queue lengths. This falls back if this is returned and uses a queue length of 0. Will only impact prior to fork.

feat: guard against EXCESS_INHIBITOR queue

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/ForceExit.tsx
src/pages/Actions/components/PartialWithdraw.tsx
src/pages/Actions/components/PullConsolidation.tsx
src/pages/Actions/components/PushConsolidation.tsx
src/pages/Actions/components/UpgradeCompounding.tsx
src/pages/Actions/utils.ts
src/utils/envVars.ts

If two transactions with the same fee are processed at the same time, if the fee were to increase after the first transaction is added, the second transaction will fail.  To reduce the likelihood of this we can add a hardcoded fee amount to each compounding and withdrawal requests. This won't work for extreme demand but is a quick and dirty implementation that will drastically reduce the likelihood in every other scenario.
Additionally, a bug was discovered where the fee amount was not returned as a decimal which resulted in failures to submit the transaction.

Append to compounding/withdrawal fee

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/ForceExit.tsx
src/pages/Actions/components/PartialWithdraw.tsx
src/pages/Actions/components/PullConsolidation.tsx
src/pages/Actions/components/PushConsolidation.tsx
src/pages/Actions/components/QueueWarning.tsx
src/pages/Actions/components/UpgradeCompounding.tsx
src/pages/Actions/components/ValidatorDetails.tsx
src/pages/Actions/index.tsx
src/styles/GlobalStyles.ts

Fixes `strong` styling to appropriately use `font-weith: 700;` using a new `text-bold` class.
Example:
Before:
After:

fix: apply font-weight:700; for strong elements

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/ValidatorDetails.tsx
src/pages/TopUp/components/ValidatorTable.tsx

The Dora API uses different statuses than those from beaconcha.in. It uses the one from https://github.com/attestantio/go-eth2-client . The source can be found on https://github.com/attestantio/go-eth2-client/blob/07599e7891634b175c498ea5c5f842a19bc29a61/api/v1/validatorstate.go#L49
This PR add the additional statuses so we can use both sets of APIs. This is mostly for visual support for the staking-launchpad.

Add dora validator statuses

---

src/components/Select.tsx
src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/PullConsolidation.tsx
src/pages/Actions/components/PushConsolidation.tsx
src/pages/Actions/components/ValidatorActions.tsx
src/pages/Actions/components/ValidatorSelector.tsx
src/pages/Actions/index.tsx
src/pages/Actions/utils.ts
src/pages/ConnectWallet/web3Utils.ts

Adds ability to consolidate a validator into one that is not associated with the connected wallet. This is done by searching the validator dropdown by a pubkey. If one is discovered, it will be selected.  Also handling messaging if the discovered validator does not have 0x02 credentials. A little safety check is also being added in this case where the user will need to type the validator index of what they are sending to. This can be easily updated if a more strenuous message is desired.
This is branched off of #750 so that should be landed first

Pectra mismatch consolidation

---

src/components/AppBar.tsx

The top up is not accessible from the hamburger menu when the resolution width is too small. This PR simply add that link in that menu.

Add missing link in hamburger

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/UpgradeCompounding.tsx
src/pages/Actions/components/ValidatorActions.tsx
src/pages/Actions/index.tsx

- Adds mainnet link to pectrified.com validator/queue status
- For non-mainnet, links to general pectrified.com as a learning resource to learn about the queues
- Adds notes to "Upgrade" flow warning user that balance over 32 will go through the activation queue and disappear from their shown balance while being processed (with link to pectrified)

feat: add activation warning and pectrified explorer links

---

src/intl/compiled/en.json
src/intl/en.json
src/pages/Actions/components/ValidatorActions.tsx
src/pages/Actions/components/ValidatorSelector.tsx
src/pages/Actions/index.tsx

Fixing issues I ran into when consolidating my validators and user report. They are separated in the three commits:
- **Remove isNascent check for target validators**: A user noted that they were unable to consolidate to a validator that was recently active. Looking at [the spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/beacon-chain.md#new-process_consolidation_request), it appears only the source validator has an activation requirement. I don't see any reference to the target: 
```python
if current_epoch < source_validator.activation_epoch + SHARD_COMMITTEE_PERIOD:
return
```
The problem is we would filter to valid source validators and then user the source validators to then filter target.
- **Will properly reset Actions when changing wallet**: When changing an …

Pectra bug fixes
